substitutions:
  devicename: cambridgeaudiocxa81
  upper_devicename: Cambridge Audio CXA81
  wifi_ap_password: Idealize|Harddisk4|Duo
  timezone: Europe/Berlin
  ntp_server: "10.10.0.33"
  area: Living Room
  mqtt_broker: "10.10.2.1"
  mqtt_port: "1883"
  static_ip: "10.10.2.212"
  gateway: "10.10.0.11"
  subnet: "255.255.252.0"
  dns: "10.10.0.33"